# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16wsZZ0TRLV7DvoRUo-onUY5Cd5BeICpL
"""

import pandas as pd

file_name = "/content/iot_sensor_raw_data_extended.csv"

df = pd.read_csv(file_name)

before = len(df)

print("===== ข้อมูลตัวอย่าง =====")
print(df.head())

print("\n===== ข้อมูลทั้งหมด =====")
print(df.info())


missing_count = df.isnull().sum()

duplicate_count = df.duplicated(
    subset=["device_id", "timestamp"]
).sum()

temp_outlier = ((df["temp_c"] < 0) | (df["temp_c"] > 50)).sum()

battery_outlier = ((df["battery"] < 0) | (df["battery"] > 100)).sum()

print("\n===== Missing Value =====")
print(missing_count)

print("\nDuplicate =", duplicate_count)
print("Temperature Outlier =", temp_outlier)
print("Battery Outlier =", battery_outlier)


df = df.drop_duplicates(
    subset=["device_id", "timestamp"]
)


df.loc[
    (df["temp_c"] < 0) | (df["temp_c"] > 50),
    "temp_c"
] = None

df.loc[
    (df["battery"] < 0) | (df["battery"] > 100),
    "battery"
] = None


df["temp_c"] = df["temp_c"].fillna(
    df["temp_c"].mean()
)

df["battery"] = df["battery"].fillna(
    df["battery"].mean()
)

df["device_id"] = df["device_id"].fillna(
    "UNKNOWN"
)

df["motion"] = df["motion"].fillna(
    "unknown"
)

df["data_quality_status"] = "Valid"

df.loc[
    df["device_id"] == "UNKNOWN",
    "data_quality_status"
] = "Missing Device ID"


output_file = "/content/cleaned_sensor_data.csv"

df.to_csv(output_file, index=False)


after = len(df)

print("\n===== Summary =====")
print("Rows before :", before)
print("Rows after  :", after)

print("\nMissing Value")
print(df.isnull().sum())

print("\nDuplicate Removed :", duplicate_count)

print("Temperature Outlier :", temp_outlier)

print("Battery Outlier :", battery_outlier)

print("\nCleaned file saved as:", output_file)